lst = list(range(10,101,10))
print('--- Somchai ---')
print('List =',lst)
print('Largest to smallest',sorted(lst,reverse=True))
print('Sum =',sum(lst))
print('Max =',max(lst))
print('Min =',min(lst))
print('Average =',sum(lst)/len(lst))
print('\n--- End Program ---')
