n = input('Enter 5 numbers separated by space: ')
ns = list(map(int,n.split(' ')))
print('Original:',ns)
print('Step 1: Add 8 and 4 to the end of the list')
ns.append(8)
ns.append(4)
print('     ',ns)
print('Step 2: insert 2 after 3 and 6 after 5')
ns.insert(1,2)
ns.insert(4,6)
print('     ',ns)
print('Step 3: remove 1 and 8')
ns.remove(1)
ns.remove(8)
print(ns)